# Generated by Django 2.2.1 on 2019-06-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_id', models.IntegerField()),
                ('catagory_1', models.CharField(max_length=15)),
                ('sub_catagory_1', models.CharField(max_length=15)),
                ('sub_catagory_2', models.CharField(max_length=15)),
                ('HH', models.CharField(max_length=1)),
                ('MM', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Distributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.IntegerField()),
                ('distributor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.IntegerField()),
                ('manufacturer_abv', models.CharField(max_length=4)),
                ('manufacturer_name', models.CharField(max_length=25)),
                ('manufacturer_sells', models.TextField()),
                ('manufacturer_website', models.TextField()),
                ('manufacturer_contact_first_name', models.CharField(max_length=15)),
                ('manufacturer_contact_last_name', models.CharField(max_length=15)),
                ('manufacturer_contact_title', models.CharField(max_length=15)),
                ('manufacturer_address', models.CharField(max_length=25)),
                ('manufacturer_city', models.CharField(max_length=15)),
                ('manufacturer_state', models.CharField(max_length=15)),
                ('manufacturer_zip_code', models.CharField(max_length=10)),
                ('manufacturer_country', models.CharField(max_length=15)),
                ('manufacturer_phone', models.CharField(max_length=15)),
                ('manufacturer_email', models.CharField(max_length=50)),
                ('manufacturer_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_name', models.CharField(max_length=25)),
                ('product_discription', models.TextField(max_length=200)),
                ('price_value', models.IntegerField()),
                ('catagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_small_world.Catagories')),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_small_world.Distributors')),
                ('product_manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_small_world.Manufacturers')),
            ],
        ),
    ]
