# Generated by Django 2.2.1 on 2019-06-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0009_auto_20190606_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributors',
            name='distributor_name',
            field=models.CharField(max_length=50),
        ),
    ]
