# Generated by Django 2.2.1 on 2019-06-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0010_auto_20190606_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagories',
            name='catagory_id',
        ),
        migrations.RemoveField(
            model_name='distributors',
            name='distributor_id',
        ),
        migrations.RemoveField(
            model_name='manufacturers',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_code',
        ),
        migrations.AlterField(
            model_name='catagories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
