# Generated by Django 2.2.1 on 2019-06-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0012_auto_20190623_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagories',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterModelOptions(
            name='distributors',
            options={'verbose_name_plural': 'Distributors'},
        ),
        migrations.AlterModelOptions(
            name='manufacturers',
            options={'verbose_name_plural': 'Manufactuers'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
