# Generated by Django 2.2.1 on 2019-06-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0014_auto_20190623_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catagories',
            new_name='catagories_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='distributor',
            new_name='distributor_id',
        ),
    ]
