# Generated by Django 2.2.1 on 2019-06-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0017_auto_20190628_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_discription',
            field=models.TextField(max_length=0, null=True),
        ),
    ]
