# Generated by Django 2.2.1 on 2019-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0002_auto_20190604_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=20),
        ),
    ]
