# Generated by Django 2.2.1 on 2019-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0007_auto_20190606_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='manufacturer_name',
            field=models.CharField(max_length=50),
        ),
    ]
