# Generated by Django 2.2.1 on 2019-06-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0011_auto_20190618_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catagories',
            new_name='catagories_id',
        ),
    ]
