# Generated by Django 2.2.1 on 2019-06-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0013_auto_20190623_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catagories_id',
            new_name='catagories',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='distributor_id',
            new_name='distributor',
        ),
    ]
