# Generated by Django 2.2.1 on 2019-06-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_small_world', '0016_auto_20190628_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='manufacturer_abv',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
